### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by ddatsh** [openzipkin/zipkin-support#12]
different computer, all win10  64, same latest chrome ,firefox  version

index page, click search

some  chrome can show,  other  blank page
all firefox blank page
 
zipkin version: docker 2.21.2 2.21.3

```
TypeError: "i is not a function"
    plural core.production.min.js:1
    e core.production.min.js:1
    e core.production.min.js:1
    e core.production.min.js:1
    v core.production.min.js:1
    value core.production.min.js:1
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    Redux 6
    pn traces-action.js:32
react-dom.production.min.js:209:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    Redux 6
    pn traces-action.js:32
```

**Comment by ddatsh** [comment]
so wired, I try virtualbox another win10 version
now my win10  x64 190041.264

**Comment by codefromthecrypt** [comment]
@ddatsh can you confirm against https://zipkin.ddatsh.com/zipkin/?endTs=1591242350339&limit=10&lookback=604800000 also? Also what is your language setting?

**Comment by ddatsh** [comment]
> @ddatsh can you confirm against https://zipkin.ddatsh.com/zipkin/?endTs=1591242350339&limit=10&lookback=604800000 also? Also what is your language setting?

yes this url ,in my firefox to open,  blank
lang=zh-cn
....oh i change to en-us,,,, problem solved

**Comment by codefromthecrypt** [comment]
problem workaround :) not solve. we will try to fix the problem with the chinese support

**Comment by ddatsh** [comment]
@jxc928

**Comment by jxc928** [comment]
emm....
In my case,
Ubuntu Server 16.04 with english. zipkin is also the default configuration with english.

In the same operation, **only the version is modified to 2.21.1**, which is completely normal.

**Comment by jxc928** [comment]
opps...language problem.

**Comment by codefromthecrypt** [comment]
you can try https://github.com/openzipkin/zipkin/pull/3106 by doing

```bash
curl -sSL https://jitpack.io/com/github/openzipkin/zipkin/zipkin-server/no-plurals-SNAPSHOT/zipkin-server-no-plurals-SNAPSHOT-exec.jar > zipkin.jar
```

which grabs from the PR.

If someone can help with translation 🙏
