### ISSUE TITLE
Conflict with graylogs data in Elasticsearch.

### ISSUE THREAD

**Issue by 007anwar** [openzipkin/zipkin-support#21]
I have Spring boot services that are sending its logs to graylog's and stored in elasticsearch, now when I am trying to add zipkin feature to my existing services I am able to see traces on zipkin but as soon as zipkin's index is created in Elasticsearch the graylog's data is getting corrupted.

**Comment by 007anwar** [comment]
When I use Graylogs and zipkin both together and as soon as zipkins index is created I get following error on dashboard of graylogs and all logs go away
```
While retrieving data for this widget, the following error(s) occurred:
Unable to perform search query: failed to create query: { "bool" : { "must" : [ { "bool" : { "filter" : [ { "match_all" : { "boost" : 1.0 } }, { "match_all" : { "boost" : 1.0 } } ], "adjust_pure_negative" : true, "boost" : 1.0 } }, { "range" : { "timestamp" : { "from" : "2020-06-25 11:48:48.443", "to" : "2020-06-25 11:53:48.443", "include_lower" : true, "include_upper" : true, "boost" : 1.0 } } }, { "terms" : { "streams" : [ "000000000000000000000001" ], "boost" : 1.0 } } ], "adjust_pure_negative" : true, "boost" : 1.0 } }.
```

 but when I manually recalculate index rage all error go away and I see logs back.

**Comment by 007anwar** [comment]
anybody here to resolve this.......

**Comment by codefromthecrypt** [comment]
maybe ask someone at graylogs? We neither control elasticsearch nor clones
of it and which APIs act differently. especially we never claimed to
support graylogs and certainly dont test with it.

you can include http output with ES_HTTP_LOGGING which might help them
figure out what is misunderstood.

https://github.com/openzipkin/zipkin/tree/master/zipkin-server#elasticsearch-storage

**Comment by 007anwar** [comment]
This issue is resolved after providing volume to mongoDb along with elasticsearch

**Comment by codefromthecrypt** [comment]
thanks for responding back to the thread!
