### ISSUE TITLE
zipkin.io domain expired

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-support#31]
renewal didn't happen on zipkin.io. We've pinged the person who had been renewing it. Meanwhile this is causing problems and some are doing workarounds which can be reverted later.

https://github.com/open-telemetry/opentelemetry-collector/pull/1417

**Comment by codefromthecrypt** [comment]
Note: we've heard Anthony renewed the domain, but still trying to verify that happened. Sadly, none of the committers have access to the domain in godaddy (under anthony's account).  Of course, we tried in the past but godaddy wouldn't authorize the switch for some reason. When things are working again, we'll of course try again.

cc @openzipkin/core in case there's someone on that distro who aren't already aware.
cc @mchandramouli in case you have some magic access to godaddy now :P

**Comment by codefromthecrypt** [comment]
@bogdandrutu can you verify? works for me now.

**Comment by jcchavezs** [comment]
open-telemetry/opentelemetry-collector#1430

**Comment by shakuzen** [comment]
Based on the pull request by @jcchavezs being approved/merged and my own verification that the site is available again, closing this as resolved. Thanks everyone!
