### ISSUE TITLE
Can't see existing data in Elasticsearch through Zipkin.

### ISSUE THREAD

**Issue by Rietty** [openzipkin/zipkin-support#38]
So I have ES set up (AWS using the AWS-ES module from openzipkin) and I am running into an issue where regardless of what ES_INDEX I set up, it does not show me existing traces that are already in my ES storage that I would like to look up. Only new traces from start-up onwards are able to be seen from Zipkin UI, instead of everything which is what is desired.

**Comment by codefromthecrypt** [comment]
anything to share on this? maybe someone else would hit a similar glitch

**Comment by Rietty** [comment]
@adriancole I'm actually not 100% sure if it's intended design or not. So I'm going to be running a test on it the next week. I did figure out one of the issues was that the index name wasn't technically matching up with what we had, since it appends the word `-span` to the index.
