### ISSUE TITLE
zipkin service missing from envoy

### ISSUE THREAD

**Issue by andrevegas** [openzipkin/zipkin-support#7]
Hi, for documentation purposes.

**Problem:**
Zipkin can consume the metrics sent but UI breaks when querying the data.
![image](https://user-images.githubusercontent.com/8179406/80168295-113f0780-8615-11ea-87e2-6cdd4cafb069.png)

**Solution:**
The cluster name MUST to be defined on envoy's config context. If it's not, the span "span.localEndpoint.serviceName" is not generated and caused the UI to break.

Define it into the config file:
`  envoy.yaml: >
    node:
      id: foo
      cluster: foo
    static_resources:
      listeners:
        ...
`

or as init params:

`
envoy -c /etc/envoy.yaml --service-cluster ${NAME}
`

relates to: https://github.com/openzipkin/zipkin/issues/3072

Cheers,

**Comment by codefromthecrypt** [comment]
great and thanks!
